# Generated by Django 4.0.4 on 2022-04-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_streamingservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='streamingservice',
            name='date',
            field=models.DateField(verbose_name='watch date'),
        ),
        migrations.AddField(
            model_name='show',
            name='creator',
            field=models.ManyToManyField(to='main_app.creator'),
        ),
    ]
